eureka:
  client:
    register-with-eureka: false

server:
  port: 8088
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: etudiants
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/etudiants/**
        - id: filieres
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/filieres/**

